const nodeOptions = [
    'State',
    'Partitions',
    'Active Features',
    'Available Features',
    'CPUAlloc',
    'CPUTot',
    'CPULoad',
    'RealMemory',
    'AllocMem',
    'FreeMem',
    'NodeName',
    'Arch',
    'CoresPerSocket',
];

const jobOptions = [
    'USER',
    'ACCOUNT',
    'JOB ID'
];

const nodeDisplayAttributes = [
    'NodeName',
    'Arch',
    'CoresPerSocket',
    'CPUAlloc',
    'CPUTot',
    'CPULoad',
    'AvailableFeatures',
    'ActiveFeatures',
    'Gres',
    'Version',
    'RealMemory',
    'AllocMem',
    'FreeMem',
    'Sockets',
    'Boards',
    'State',
    'ThreadsPerCore',
    'TmpDisk',
    'Weight',
    'Owner',
    'MCS_label',
    'Partitions',
    'BootTime',
    'SlurmdStartTime',
    'CfgTRES',
    'AllocTRES',
    'CapWatts',
    'CurrentWatts',
    'AveWatts',
    'ExtSensorsJoules',
    'ExtSensorsWatts',
    'ExtSensorsTemp',
    'Reason',
    'Job ID',
    'Account',
    'User',
    'Display Graph',
]

export {nodeOptions, jobOptions, nodeDisplayAttributes};